CREATE TABLE order_statuses(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE orders(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fileName text NOT NULL,
    storingName text NOT NULL,
    creation_date date NOT NULL,
    user_id int NOT NULL,
    status_id int NOT NULL,
    download_link text,
    is_deleted bool NOT NULL,
    FOREIGN KEY (status_id) REFERENCES order_statuses (id)
);

CREATE TABLE payment_types(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text UNIQUE NOT NULL
);

CREATE TABLE payments(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL,
    type_id int NOT NULL,
    date timestamp NOT NULL,
    FOREIGN KEY (type_id) REFERENCES payment_types (id)
);

CREATE TABLE subscription_types(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE subscriptions(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL,
    type_id int NOT NULL,
    sub_expire_date timestamp,
    FOREIGN KEY (type_id) REFERENCES subscription_types (id)
);

INSERT INTO order_statuses (name) VALUES ('in queue');
INSERT INTO order_statuses (name) VALUES ('in progress');
INSERT INTO order_statuses (name) VALUES ('error');
INSERT INTO order_statuses (name) VALUES ('success');

INSERT INTO payment_types (name) VALUES ('sub-premium-month');

INSERT INTO subscription_types (name) VALUES ('premium');
