CREATE TABLE order_statuses(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text UNIQUE NOT NULL CHECK ( name <> '' )
);

CREATE TABLE orders(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fileName text NOT NULL CHECK ( fileName <> '' ),
    storingName text NOT NULL CHECK ( storingName <> '' ),
    creation_date date NOT NULL,
    user_id int NOT NULL,
    status_id int NOT NULL,
    download_link text,
    is_deleted bool NOT NULL,
    FOREIGN KEY (status_id) REFERENCES order_statuses (id)
);

CREATE TABLE payment_types(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text UNIQUE NOT NULL CHECK ( name <> '' )
);

CREATE TABLE payments(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL,
    type_id int NOT NULL,
    date timestamp NOT NULL,
    FOREIGN KEY (type_id) REFERENCES payment_types (id)
);

CREATE TABLE subscription_types(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text UNIQUE NOT NULL CHECK ( name <> '' )
);

CREATE TABLE subscriptions(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL,
    type_id int NOT NULL,
    sub_expire_date timestamp,
    FOREIGN KEY (type_id) REFERENCES subscription_types (id)
);
