env: "dev"
http_server:
  host: "0.0.0.0"
  port: 8080
  timeout: 4s
  idle_timeout: 30s
db:
  name: "cloud_render_api"
  user: "user"
  password: "password"
  host: "postgres"
  port: "5432"
  migrations_path: "file://../../../migrations/api/postgres"
redis:
  address: "redis:6379"
  password: "password"
  queue_name: "render-list"
  priority_queue_name: "subscribed-render-list"
paths:
  user: "/user"
  subscribe: "/susbcribe"
external:
  sso_user_info: "http://sso:8001/info/%d"
payments:
  sub_premium_month: "sub-premium-month"
subscriptions:
  premium: "premium"
