env: "dev"
http_server:
  host: "0.0.0.0"
  port: 8080
  timeout: 4s
  idle_timeout: 30s
db:
  name: "cloud_render_api"
  user: "user"
  password: "password"
  host: "postgres"
  port: "5432"
  migrations_path: "file://../../../migrations/api/postgres"
paths:
  user: "/user"
external:
  sso_user_info: "http://sso:8001/info/%d"
