env: "dev"
http_server:
  host: "0.0.0.0"
  port: 8082
  timeout: 4s
  idle_timeout: 30s
db:
  name: "cloud_render_api"
  user: "user"
  password: "password"
  host: "postgres"
  port: "5432"
redis:
  address: "redis:6379"
  password: "password"
  queue_name: "render-list"
  priority_queue_name: "subscribed-render-list"
order_statuses:
  in_queue: "in queue"
  in_progress: "in progress"
  error: "error"
  success: "success"
