env: "local"
http_server:
  host: "localhost"
  port: 8080
  timeout: 4s
  idle_timeout: 30s
db:
  name: "cloud_render_api"
  user: "user"
  password: "password"
  host: "localhost"
  port: "5432"
  migrations_path: "file://../../../migrations/api/postgres"
