env: "local"
http_server:
  host: "localhost"
  port: 8081
  timeout: 4s
  idle_timeout: 30s
db:
  name: "cloud_render_auth"
  user: "user"
  password: "password"
  host: "localhost"
  port: "5432"
  migrations_path: "file://../../../migrations/auth/postgres"
paths:
  signup: "/signup"
  signin: "/signin"
  refresh: "/refresh"
  edit: "/user/edit"
  info: "/info"
  placeholders:
    id: "/{id}"
