CREATE TABLE users(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login text UNIQUE NOT NULL CHECK ( login <> '' ),
    email text UNIQUE NOT NULL CHECK ( email <> '' ),
    password text NOT NULL CHECK ( password <> '' ),
    refresh_token text
);
